apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anime-service 
  template:
    metadata:
      labels:
        app: anime-service 
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: api-gateway 
          image: nebsec/aniflow:anime-ms-latest
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_ROOT_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_ROOT_PASS